name: Build ESP32 Firmware

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup ESP-IDF
        uses: espressif/setup-esp-idf@v1.4.0
        with:
          version: v5.3

      - name: Build firmware
        run: |
          idf.py set-target esp32s3
          idf.py build
