name: ESP32 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup ESP-IDF
      uses: espressif/setup-esp-idf@v1
      with:
        version: v5.1

    - name: Build
      run: |
        idf.py set-target esp32s3
        idf.py build
