name: ESP32-S3 OTA Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up ESP-IDF
        uses: espressif/setup-esp-idf@v1
        with:
          esp_idf_version: v5.3.1

      - name: Build firmware
        working-directory: simple_ota_example
        run: |
          idf.py set-target esp32s3
          idf.py build

      - name: Upload simple_ota.bin
        uses: actions/upload-artifact@v4
        with:
          name: simple_ota_bin
          path: simple_ota_example/build/simple_ota.bin
