name: Build ESP32

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up ESP-IDF
      uses: espressif/setup-esp-idf@v1
      with:
        version: v5.1

    - name: Build the project
      run: idf.py build
