name: ESP32-S3 CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build using ESP-IDF CI Action
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.3.1
        target: esp32s3
        path: .

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: esp32-firmware
        path: |
          build/bootloader/bootloader.bin
          build/partition_table/partition-table.bin
          build/*.bin
          build/*.elf
