name: ESP-IDF Build

on:
  push:
    paths:
      - 'simple_ota_example/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ESP-IDF
        uses: espressif/setup-esp-idf@v2
        with:
          version: latest

      - name: Build Project
        run: |
          cd simple_ota_example
          idf.py fullclean
          idf.py build
