name: ESP32 OTA CI Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up ESP-IDF
        uses: espressif/setup-idf@v1
        with:
          esp-idf-version: v5.1.2  # Use latest supported version

      - name: Build ESP32 project
        working-directory: simple_ota_example
        run: |
          idf.py fullclean
          idf.py build
