name: ESP32-S3 OTA Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build ESP32 project
        uses: espressif/esp-idf-ci-action@v1
        with:
          target: esp32s3
          path: simple_ota_example

      - name: Upload OTA binary
        uses: actions/upload-artifact@v4
        with:
          name: simple_ota_bin
          path: simple_ota_example/build/simple_ota.bin
